# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1To1Rating' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for 1To1Rating

    pod 'AFNetworking', '~> 3.0'
    pod 'DGActivityIndicatorView'
#    pod 'NVActivityIndicatorView'
#    pod 'Alamofire', '~> 4.5.0'

#    pod 'IQKeyboardManager'
    pod 'TPKeyboardAvoiding'
end
